ALTER TABLE offers ADD COLUMN description TEXT;
ALTER TABLE offers ADD COLUMN location TEXT;
ALTER TABLE offers ADD COLUMN currency TEXT;
ALTER TABLE offers ADD COLUMN price_json TEXT;
ALTER TABLE offers ADD COLUMN terms_json TEXT;
ALTER TABLE offers ADD COLUMN images_json TEXT;
ALTER TABLE offers ADD COLUMN availability_method TEXT;
ALTER TABLE offers ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE offers ADD COLUMN approved_at TEXT;
ALTER TABLE bookings ADD COLUMN offer_id TEXT;
ALTER TABLE bookings ADD COLUMN customer_token TEXT;
ALTER TABLE bookings ADD COLUMN supplier_token TEXT;
ALTER TABLE bookings ADD COLUMN booking_data_json TEXT;
CREATE TABLE supplier_reviews (id TEXT PRIMARY KEY, supplier_id TEXT NOT NULL REFERENCES suppliers(id), offer_id TEXT NOT NULL REFERENCES offers(id), secure_token TEXT NOT NULL UNIQUE, version INTEGER NOT NULL, status TEXT NOT NULL, change_request TEXT, created_at TEXT NOT NULL, decided_at TEXT);
CREATE INDEX idx_supplier_reviews_token ON supplier_reviews(secure_token);
CREATE TABLE availability_requests (id TEXT PRIMARY KEY, booking_id TEXT NOT NULL REFERENCES bookings(id), method TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, decided_at TEXT);
CREATE TABLE communications (id TEXT PRIMARY KEY, booking_id TEXT, supplier_id TEXT, channel TEXT NOT NULL, direction TEXT NOT NULL, status TEXT NOT NULL, metadata_json TEXT, created_at TEXT NOT NULL);
CREATE TABLE learning_events (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('SIGNAL','DECISION','ACTION','RESULT','LESSON','RULE')), detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE UNIQUE INDEX idx_bookings_customer_token ON bookings(customer_token);
CREATE UNIQUE INDEX idx_bookings_supplier_token ON bookings(supplier_token);
