
import maluda from './maluda-zanzibar-final-worker.js';
import nch from './qa-click-wrapper.js';
import app from './index.js';
import { supplierPreview, supplierCss } from './supplier-pages.js';
import { globalExplore, globalExploreCss } from './global-explore.js';
import { globalHome, globalHomeCss } from './global-home.js';
import { yacoutReview, yacoutCss } from './yacout-review.js';
import { capeCarToursPage } from './cape-car-tours-worker.js';

const spicePhoto='https://commons.wikimedia.org/wiki/Special:Redirect/file/People_at_the_marketplace_of_the_Stone_Town_-_Zanzibar_(22227853516).jpg';
const badPradoPhoto='https://res.cloudinary.com/cpp8vjzo/image/upload/v1786015986/maluda-car-rental/cars/yvbdca8pakpu5jpobhoj.webp';
const zanzibarCss=`.destination-hero{position:relative;min-height:520px;border-radius:26px;overflow:hidden;margin-bottom:24px;background:#0b172a;color:#fff;display:flex;align-items:flex-end;isolation:isolate;box-shadow:0 20px 55px rgba(8,27,55,.18)}.destination-hero:before{content:'';position:absolute;inset:0;background-image:linear-gradient(90deg,rgba(4,14,28,.84),rgba(4,14,28,.18)),url('https://upload.wikimedia.org/wikipedia/commons/8/8d/Nungwi_%282010-011-1318-T%29.jpg');background-size:cover;background-position:center 48%;z-index:-2}.destination-hero:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,rgba(4,14,28,.48),transparent 48%);z-index:-1}.destination-hero__content{padding:clamp(28px,5vw,58px);max-width:780px}.destination-hero__eyebrow{display:inline-flex;padding:7px 11px;border-radius:999px;background:#ffffff29;border:1px solid #ffffff42;font-size:12px;font-weight:900;letter-spacing:.12em}.destination-hero h1{font-size:clamp(44px,7vw,82px);line-height:.96;letter-spacing:-.055em;margin:18px 0 14px}.destination-hero p{font-size:clamp(17px,2vw,21px);line-height:1.6;color:#f3f7fb;max-width:660px}.destination-hero__actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:24px}.destination-hero__credit{position:absolute;right:16px;bottom:12px;font-size:11px;color:#fff;background:#0006;padding:6px 8px;border-radius:8px}.destination-hero__credit a{text-decoration:underline;color:#fff}body{background:linear-gradient(180deg,#f7fbfc,#fff9ef 42%,#f8efe0);color:#092642}.card{border-color:#e4d4bc!important;box-shadow:0 14px 34px rgba(70,52,24,.11)!important}.card-body{background:linear-gradient(155deg,#fff9ed,#f8ead4)!important;border-top:1px solid #ead8bb}.card-body h3{color:#08233e!important;font-weight:900}.card-body .muted{color:#526574!important}.card-body .price{color:#0a5f63!important}.card-body .btn{background:linear-gradient(135deg,#138e94,#08747c)!important}.carvisual{background:linear-gradient(145deg,#d8f1ef,#f7e3bf)!important}.panel,.details,.detail,.region-intro{background:#fffcf6!important;border-color:#eadfce!important}.notice,.warning{background:linear-gradient(90deg,#fff4d5,#fff9eb)!important;border-left-color:#e39120!important}.prado-safe{height:210px;display:grid;place-items:center;text-align:center;padding:24px;background:linear-gradient(145deg,#0d6870,#159aa0 55%,#efb45c);color:#fff;font-size:24px;font-weight:950}.prado-safe small{display:block;font-size:12px;margin-top:8px;letter-spacing:.12em}.experience-visual{position:relative}.experience-visual:after{content:'CULTURAL EXPERIENCE';position:absolute;left:14px;bottom:14px;padding:7px 10px;border-radius:999px;background:#07182fd6;color:#fff;font-size:11px;font-weight:900;letter-spacing:.09em}@media(max-width:700px){.destination-hero{min-height:500px}.destination-hero__content{padding:28px 22px 58px}.prado-safe{height:230px}}`;
const heroMarkup=`<section class="destination-hero"><div class="destination-hero__content"><span class="destination-hero__eyebrow">TOETI ZANZIBAR · TANZANIA</span><h1>Explore Zanzibar with TOETI</h1><p>From Stone Town to the turquoise coast, discover Zanzibar with trusted local rental cars and experiences — with local suppliers keeping final control of availability.</p><div class="destination-hero__actions"><a class="btn alt" href="/destination/zanzibar?type=CAR_RENTAL">Rental Cars</a><a class="btn" href="/destination/zanzibar?type=EXPERIENCE">Experiences</a></div></div><div class="destination-hero__credit">Photo: <a href="https://commons.wikimedia.org/wiki/File:Nungwi_(2010-011-1318-T).jpg">Moongateclimber / Wikimedia Commons</a> · CC BY 3.0</div></section>`;

function shellWith(shell,main,css){return shell.replace(/<main\b[^>]*>[\s\S]*<\/main>/,main).replace('</style>',`${css}</style>`).replace('href="/destination/zanzibar">Explore','href="/explore">Explore');}

function publicMeta(html,{title,description,canonical}){
 return html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${title}</title>`).replace('</head>',`<meta name="description" content="${description}"><meta name="robots" content="index,follow"><link rel="canonical" href="${canonical}"></head>`);
}

export default {async fetch(request,env,ctx){
 const url=new URL(request.url);
 if(request.method==='GET'&&['/supplier/cape-car-tours','/experiences/cape-car-tours'].includes(url.pathname))return new Response(capeCarToursPage(),{status:200,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow'}});
 if(url.pathname==='/supplier/maluda-zanzibar'||url.pathname.startsWith('/cars/')||url.pathname.startsWith('/request/')) return maluda.fetch(request,env,ctx);
 if(url.pathname==='/supplier/nch-fiji'||url.pathname==='/supplier/nch-rentals-fiji'||url.pathname==='/supplier/undefined'||url.pathname.startsWith('/nch/request')){const mapped=url.pathname.startsWith('/nch/request')?new URL('/request'+url.search,url):url;return nch.fetch(new Request(mapped,request),env,ctx);}
 if(request.method==='GET'&&url.pathname==='/supplier/yacout-marrakech-review'){
   const shell=await app.fetch(new Request(new URL('/partners',url),request),env,ctx);const base=shellWith(await shell.text(),yacoutReview(),yacoutCss);const h=new Headers(shell.headers);h.set('cache-control','no-store');h.set('x-robots-tag','noindex, nofollow');return new Response(base,{status:200,headers:h});
 }
 if(request.method==='GET'&&(url.pathname==='/'||url.pathname==='/explore')){
   const shell=await app.fetch(new Request(new URL('/partners',url),request),env,ctx);let base=await shell.text();
   const isHome=url.pathname==='/';
   base=shellWith(base,isHome?globalHome():globalExplore(),isHome?globalHomeCss:globalExploreCss);
   base=base.replace('<a href="/demo">Demo flow</a>','').replace('Launch / founding-partner phase · No invented traffic, bookings or universal commission.','Local travel, connected globally.');
   if(isHome) base=base.replace('<nav class="navlinks">','<nav class="navlinks"><a href="/#destinations">Destinations</a><a href="/explore#cars">Cars</a><a href="/explore#experiences">Tours &amp; Experiences</a><a href="/explore#longstay">Long-stay</a>');
   base=publicMeta(base,isHome?{title:'TOETI Global — Rental Cars, Tours & Long-Stay Cars',description:'Explore supplier-approved rental cars, tours and long-stay car rentals with TOETI Global.',canonical:'https://toeti-global-car-rental.sarose.workers.dev/'}:{title:'Explore TOETI Destinations — Cars, Tours & Long-Stay',description:'Explore customer-ready TOETI destinations, local rental cars, tours and verified long-stay car rentals.',canonical:'https://toeti-global-car-rental.sarose.workers.dev/explore'});
   const h=new Headers(shell.headers);const csp=h.get('content-security-policy');if(csp)h.set('content-security-policy',csp.replace("script-src 'unsafe-inline'","script-src 'unsafe-inline' https://unpkg.com").replace('https://res.cloudinary.com','https://res.cloudinary.com https://upload.wikimedia.org https://commons.wikimedia.org https://unpkg.com'));h.set('cache-control','no-store');return new Response(base,{status:200,headers:h});
 }
 const preview=supplierPreview(url.pathname);
 let response;
 if(request.method==='GET'&&preview){
   const shell=await app.fetch(new Request(new URL('/partners',url),request),env,ctx); let base=await shell.text();
   base=shellWith(base,preview,supplierCss);
   const h=new Headers(shell.headers);const csp=h.get('content-security-policy');if(csp)h.set('content-security-policy',csp.replace('https://res.cloudinary.com','https://res.cloudinary.com https://upload.wikimedia.org https://commons.wikimedia.org'));h.set('cache-control','no-store');h.set('x-robots-tag','noindex, nofollow');return new Response(base,{status:200,headers:h});
 }
 if(request.method==='GET'&&url.pathname==='/zanzibar-car-rental'){
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Zanzibar Car Rental from USD 25/day | TOETI</title><meta name="description" content="Explore Zanzibar by rental car from USD 25/day. Compare six supplier-approved vehicles and request availability through TOETI."><meta name="robots" content="index,follow"><link rel="canonical" href="https://toeti-global-car-rental.sarose.workers.dev/zanzibar-car-rental"><style>body{margin:0;font-family:Inter,Arial,sans-serif;background:#f7f4ee;color:#10243d}main{max-width:900px;margin:auto;padding:56px 22px}h1{font-size:clamp(38px,7vw,72px);line-height:.98;margin:.2em 0}h2{margin-top:42px}.eyebrow{letter-spacing:.15em;text-transform:uppercase;font-weight:800;color:#b4772c}.lead{font-size:20px;line-height:1.6;max-width:760px}.box{background:white;border-radius:22px;padding:24px;margin:28px 0;box-shadow:0 12px 40px #10243d12}.cta{display:inline-block;background:#10243d;color:white;text-decoration:none;padding:16px 22px;border-radius:999px;font-weight:800}.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.fact{background:#fff;padding:18px;border-radius:16px}footer{margin-top:48px;color:#657184}</style></head><body><main><div class="eyebrow">TOETI · Zanzibar</div><h1>Zanzibar car rental, without the guesswork.</h1><p class="lead">Explore the island at your own pace. TOETI currently offers six supplier-approved vehicles from USD 25/day. You send a request; the local supplier confirms availability.</p><div class="facts"><div class="fact"><b>From USD 25/day</b><br>Six approved vehicles</div><div class="fact"><b>USD 25 permit</b><br>Zanzibar driving permit</div><div class="fact"><b>Request to book</b><br>No fake instant availability</div></div><div class="box"><h2>What to know before driving</h2><p>Zanzibar drives on the left. A local driving permit is required for the TOETI supplier offer and costs USD 25. Pickup at Airport, Seaport or Stone Town is free; outside Stone Town the supplier-confirmed one-way fee is USD 10.</p><p>Free cancellation is available up to 48 hours before pickup. A 3.5% payment-provider fee may apply to cancellations.</p></div><h2>Choose your Zanzibar car</h2><p>See the current vehicle selection and send your dates. Availability is confirmed by the local supplier before the rental is final.</p><a class="cta" href="/supplier/maluda-zanzibar?utm_source=google&utm_medium=organic&utm_campaign=zanzibar_car_rental_seo&utm_content=guide">See cars & request availability →</a><footer>TOETI Global · Rental Cars · Tours · Long Stay</footer></main></body></html>`;
 return new Response(html,{status:200,headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}});
 }
 if(request.method==='GET'&&url.pathname==='/demo') return new Response('Not found',{status:404,headers:{'content-type':'text/plain; charset=utf-8','x-robots-tag':'noindex, nofollow'}});
 if(request.method==='GET'&&url.pathname==='/partners'){
   response=await app.fetch(request,env,ctx);let body=await response.text();body=publicMeta(body,{title:'Partner with TOETI Global',description:'Partner with TOETI to reach international travellers while keeping control of inventory, pricing and availability.',canonical:'https://toeti-global-car-rental.sarose.workers.dev/partners'});body=body.replace('TOETI FOUNDING SUPPLIERS','TOETI SUPPLIER NETWORK').replace('founding-supplier','supplier').replace('<a class="btn ghost" href="/demo">See the working demo</a>','').replace('Launch / founding-partner phase · No invented traffic, bookings or universal commission.','Local travel, connected globally.').replace('<a href="/demo">Demo flow</a>','');const h=new Headers(response.headers);h.set('cache-control','no-store');return new Response(body,{status:200,headers:h});
 }
 response=await app.fetch(request,env,ctx);
 const isZanzibar=url.pathname==='/destination/zanzibar'||url.pathname.startsWith('/offers/');
 if(request.method!=='GET'||!isZanzibar)return response;
 const ct=response.headers.get('content-type')||'';if(!ct.includes('text/html'))return response;
 let body=await response.text();body=body.replace('</style>',`${zanzibarCss}</style>`).replace('href="/destination/zanzibar">Explore','href="/explore">Explore').replace('<a href="/demo">Demo flow</a>','').replace('Launch / founding-partner phase · No invented traffic, bookings or universal commission.','Local travel, connected globally.');
 if(url.pathname==='/destination/zanzibar'){
  body=body.replace(/<section class="welcome">[\s\S]*?<\/section>/,heroMarkup);
  body=body.replace(`<img src="${badPradoPhoto}" alt="Toyota Prado in Zanzibar" loading="lazy">`,`<div class="prado-safe">TOYOTA PRADO<small>ZANZIBAR · PHOTO COMING SOON</small></div>`);
  body=body.replace('<div class="carvisual">TOUR</div><div class="card-body">',`<div class="carvisual experience-visual"><img src="${spicePhoto}" alt="Stone Town cultural experience in Zanzibar" loading="lazy"></div><div class="card-body">`);
 }
 if(url.pathname.includes('veh_prado'))body=body.replace(`<img src="${badPradoPhoto}"`,`<span class="prado-safe">TOYOTA PRADO<small>ZANZIBAR · PHOTO COMING SOON</small></span><img style="display:none" src="${badPradoPhoto}"`);
 const h=new Headers(response.headers);const csp=h.get('content-security-policy');if(csp)h.set('content-security-policy',csp.replace('https://res.cloudinary.com','https://res.cloudinary.com https://upload.wikimedia.org https://commons.wikimedia.org'));h.set('cache-control','no-store');return new Response(body,{status:response.status,statusText:response.statusText,headers:h});
}};
