import { secureToken } from './domain.js';

const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

export async function supplierReviewPage(token,env){
  const row=await env.DB.prepare(`SELECT r.status review_status,r.version,r.change_request,o.*,s.name supplier_name FROM supplier_reviews r JOIN offers o ON o.id=r.offer_id JOIN suppliers s ON s.id=r.supplier_id WHERE r.secure_token=?`).bind(token).first();
  if(!row)return new Response('<h1>Review link unavailable</h1>',{status:404,headers:{'content-type':'text/html; charset=utf-8'}});
  let terms={},price={};try{terms=JSON.parse(row.terms_json)||{};price=JSON.parse(row.price_json)||{}}catch{}
  const cards=[['Type',row.type],['Price',JSON.stringify(price)],['Availability',row.availability_method],...Object.entries(terms)].map(([k,v])=>`<div class="card"><b>${esc(k)}</b><p>${esc(Array.isArray(v)?v.join(', '):v)}</p></div>`).join('');
  const controls=row.review_status==='PENDING'?`<section><h2>Your decision</h2><textarea id="notes" rows="4" placeholder="Describe requested changes"></textarea><div class="actions"><button data-action="APPROVE">Approve listing</button><button class="outline" data-action="REQUEST_CHANGES">Request changes</button></div><p id="message"></p></section>`:row.review_status==='CHANGES_REQUESTED'?`<section><h2>Changes requested</h2><p>${esc(row.change_request)}</p><button id="revise">Create corrected version</button></section>`:`<section><h2>Approved and recorded</h2><p>The approved demo offer is now public.</p><a class="button" href="/offers/${esc(row.id)}">Open live demo offer</a></section>`;
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TOETI supplier review</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#0b172a;font:16px Inter,system-ui,sans-serif}header{padding:22px max(5vw,20px);background:#081b37;color:#fff;font-weight:900;letter-spacing:.13em}.wrap{width:min(1050px,calc(100% - 30px));margin:50px auto}.top{display:flex;justify-content:space-between;gap:20px;align-items:start}.kicker{color:#6249ca;font-size:12px;font-weight:900;letter-spacing:.14em}.status{padding:8px 11px;border-radius:99px;background:#e9edf5;font-weight:900}h1{font-size:clamp(36px,6vw,68px);line-height:1;margin:14px 0}.notice,section{padding:22px;background:#fff;border:1px solid #dfe6ef;border-radius:18px;margin:22px 0}.notice{background:#fff4d5;border-color:#e4c66a}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.card{padding:18px;background:#fff;border:1px solid #dfe6ef;border-radius:15px}.card p{color:#657287;line-height:1.5}textarea{width:100%;padding:12px;border:1px solid #b9c5d5;border-radius:10px;font:inherit}.actions{display:flex;gap:10px;margin-top:14px}button,.button{border:0;border-radius:11px;padding:13px 17px;background:#6b52d7;color:#fff;font-weight:850;cursor:pointer;text-decoration:none;display:inline-block}.outline{background:#fff;color:#263650;border:1px solid #bdc7d5}@media(max-width:650px){.grid{grid-template-columns:1fr}.top{display:block}.status{display:inline-block;margin-top:10px}}</style></head><body><header>TOETI GLOBAL · SUPPLIER REVIEW</header><main class="wrap"><div class="top"><div><div class="kicker">SECURE DEMO REVIEW · VERSION ${row.version}</div><h1>${esc(row.name)}</h1><p>${esc(row.supplier_name)} · ${esc(row.location)}</p></div><span class="status">${esc(row.review_status)}</span></div><p class="notice"><b>DEMO / EXAMPLE:</b> this is not a real supplier approval or commercial listing.</p><div class="grid">${cards}</div>${controls}</main><script>document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const r=await fetch('/api/supplier-reviews/${token}/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:b.dataset.action,notes:document.querySelector('#notes').value})});const d=await r.json();if(r.ok)location.reload();else document.querySelector('#message').textContent=d.error});const revise=document.querySelector('#revise');if(revise)revise.onclick=async()=>{revise.disabled=true;const r=await fetch('/api/supplier-reviews/${token}/revise',{method:'POST'});const d=await r.json();if(r.ok)location.href=d.reviewUrl;else alert(d.error)};</script></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'x-content-type-options':'nosniff'}});
}

export async function reviseSupplierReview(token,env){
  const row=await env.DB.prepare(`SELECT r.offer_id,r.supplier_id,r.version,r.status,o.terms_json FROM supplier_reviews r JOIN offers o ON o.id=r.offer_id WHERE r.secure_token=?`).bind(token).first();
  if(!row)return json({error:'Invalid review token.'},404);
  if(row.status!=='CHANGES_REQUESTED')return json({error:'Only a change request can create a revised version.'},409);
  const ts=new Date().toISOString(),newToken=secureToken(),reviewId=crypto.randomUUID(),version=row.version+1;
  let terms={};try{terms=JSON.parse(row.terms_json)||{}}catch{}
  terms.revisionNote='TOETI applied the supplier-requested correction for review.';
  await env.DB.batch([
    env.DB.prepare(`UPDATE offers SET status='SUPPLIER_REVIEW',version=?,terms_json=?,updated_at=? WHERE id=?`).bind(version,JSON.stringify(terms),ts,row.offer_id),
    env.DB.prepare(`INSERT INTO supplier_reviews(id,supplier_id,offer_id,secure_token,version,status,created_at) VALUES(?,?,?,?,?,?,?)`).bind(reviewId,row.supplier_id,row.offer_id,newToken,version,'PENDING',ts),
    env.DB.prepare(`INSERT INTO audit_events(id,entity_type,entity_id,action,source,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),'offer',row.offer_id,'DRAFT_REVISED','DEMO',JSON.stringify({version}),ts),
    env.DB.prepare(`INSERT INTO audit_events(id,entity_type,entity_id,action,source,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),'supplier_review',reviewId,'SUPPLIER_REVIEW_SENT','DEMO',JSON.stringify({offerId:row.offer_id,version}),ts)
  ]);
  return json({reviewUrl:`/supplier/demo/review/${newToken}`,version},201);
}
