
const groups=[
['A','Dacia Sandero · Dacia Logan · Kia Picanto',['1–4 days','€30 / €45'],['5–8 days','€25 / €40'],['9–21 days','€23 / €35'],['21+ days','€20 / €30'],'No deposit'],
['B','Renault Clio 5 · Peugeot 208',['1–4 days','€35 / €50'],['5–8 days','€30 / €47'],['9–21 days','€27 / €43'],['21+ days','€25 / €37'],'No deposit'],
['C','Dacia Duster · Dacia Jogger 7 seats · Citroën C3 Aircross',['1–4 days','€45 / €65'],['5–8 days','€40 / €60'],['9–21 days','€35 / €55'],['21+ days','€30 / €50'],'Deposit/deductible: €700'],
['D','Peugeot 3008 · Kia Sportage',['1–4 days','€70 / €80'],['5–8 days','€60 / €70'],['9–21 days','€50 / €60'],['21+ days','€40 / €55'],'Deposit/deductible: €1,200']
];
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
export function yacoutReview(){const cards=groups.map(g=>`<article class="yr-card"><div class="yr-cat">CATÉGORIE ${g[0]}</div><h3>${esc(g[1])}</h3><div class="yr-rates">${g.slice(2,6).map(r=>`<div><small>${r[0]}</small><b>${r[1]}</b><em>normale / haute</em></div>`).join('')}</div><p class="yr-deposit">${g[6].replace('No deposit','Sans dépôt').replace('Deposit/deductible:','Dépôt/franchise :')}</p></article>`).join('');return `<main class="yr"><section class="yr-hero"><span>REVUE PRIVÉE DU FOURNISSEUR · MARRAKECH</span><h1>Yacout Tours</h1><p>Présentation des voitures préparée uniquement à partir des informations fournies par Yacout Tours pour la revue TOETI.</p><strong>PRÊT POUR LA REVUE DU FOURNISSEUR</strong></section><section class="yr-intro"><div><span>STRUCTURE TARIFAIRE FOURNIE PAR LE FOURNISSEUR</span><h2>Quatre catégories de véhicules.</h2></div><p>Les tarifs ci-dessous sont en EUR/jour. Chaque paire indique la saison normale / haute saison. Yacout a confirmé les tarifs 2026 et les dates de saison actualisées ci-dessous.</p></section><section class="yr-grid">${cards}</section><section class="yr-facts"><div><b>Saison normale</b><p>26 août 2026 – 24 juin 2027</p></div><div><b>Haute saison</b><p>25 juin 2027 – 26 août 2027</p></div><div><b>Kilométrage</b><p>Kilométrage illimité</p></div><div><b>Disponibilité</b><p>Les demandes de réservation peuvent être envoyées par e-mail ou WhatsApp pour confirmation par Yacout.</p></div></section><section class="yr-note"><h2>À VÉRIFIER AVANT ACTIVATION</h2><p>Merci de vérifier les catégories de véhicules, les tarifs journaliers, les dates de saison et la présentation du dépôt/de la franchise. La disponibilité réelle reste confirmée par Yacout Tours. Cette page ne propose ni paiement client ni réservation instantanée.</p></section></main>`;}
export const yacoutCss=`body{background:linear-gradient(180deg,#f7fafc,#fff8ec)!important;color:#0a2440}.yr{width:min(1180px,calc(100% - 36px));margin:auto;padding:38px 0 72px}.yr-hero{min-height:440px;padding:clamp(30px,6vw,66px);border-radius:28px;display:flex;flex-direction:column;justify-content:end;color:#fff;background:radial-gradient(circle at 80% 20%,#36b5c655,transparent 25%),linear-gradient(135deg,#061a34,#0c4f67 60%,#a86a2c);box-shadow:0 24px 65px #10253a33}.yr-hero>span,.yr-intro span,.yr-cat{font-size:11px;font-weight:950;letter-spacing:.14em}.yr-hero>span{color:#8ee8f1}.yr-hero h1{font-size:clamp(48px,7vw,82px);letter-spacing:-.055em;line-height:.95;margin:15px 0}.yr-hero p{max-width:680px;font-size:18px;line-height:1.6;color:#e7f0f3}.yr-hero strong{margin-top:18px;width:max-content;padding:9px 12px;border-radius:9px;background:#f0bb58;color:#352100;font-size:12px}.yr-intro{display:flex;justify-content:space-between;gap:28px;align-items:end;padding:50px 4px 22px}.yr-intro span,.yr-cat{color:#0d7c80}.yr-intro h2{font-size:42px;margin:7px 0}.yr-intro p{max-width:530px;color:#5d6d7d;line-height:1.6}.yr-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.yr-card{padding:25px;border-radius:22px;background:#fff;border:1px solid #e4d8c6;box-shadow:0 13px 35px #503b1814}.yr-card h3{font-size:21px;line-height:1.35;min-height:58px}.yr-rates{display:grid;grid-template-columns:1fr 1fr;gap:10px}.yr-rates div{padding:13px;border-radius:13px;background:#f5f8fa}.yr-rates small,.yr-rates em{display:block;color:#687788;font-size:11px}.yr-rates b{display:block;font-size:18px;margin:4px 0}.yr-rates em{font-style:normal}.yr-deposit{font-weight:850;color:#8a5618}.yr-facts{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:20px}.yr-facts div{padding:20px;border-radius:17px;background:#0a2440;color:#fff}.yr-facts p{color:#d6e2ed;line-height:1.5}.yr-note{margin-top:20px;padding:25px;border-left:4px solid #13868c;border-radius:12px;background:#eaf8f6}.yr-note p{color:#526575;line-height:1.6}@media(max-width:760px){.yr-grid,.yr-facts{grid-template-columns:1fr 1fr}.yr-intro{align-items:flex-start;flex-direction:column}}@media(max-width:520px){.yr{width:calc(100% - 24px)}.yr-hero{min-height:450px;padding:28px 22px}.yr-grid,.yr-facts{grid-template-columns:1fr}.yr-rates{grid-template-columns:1fr 1fr}.yr-card h3{min-height:0}}`;